<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.2.1.20" />
    <PackageReference Include="SocketIOClient" Version="4.0.5" />
  </ItemGroup>

</Project>
